name: EventPulse CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install backend dependencies
        working-directory: ./server
        run: npm ci

      - name: Install frontend dependencies
        working-directory: ./client
        run: npm ci

      - name: Build frontend
        working-directory: ./client
        run: npm run build

      - name: Validate backend syntax
        working-directory: ./server
        run: node --check index.js

      - name: Log in to Docker Hub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.udayakumar27 }}
          password: ${{ secrets.Udaya892527 }}

      - name: Build and push Docker image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v6
        with:
          context: ./server
          push: true
          tags: |
            ${{ secrets.udayakumar27 }}/eventpulse-backend:${{ github.sha }}
            ${{ secrets.udayakumar27 }}/eventpulse-backend:latest

      - name: Security audit
        working-directory: ./server
        run: npm audit --omit=dev --audit-level=high